#%RAML 0.8
title: WebConsumerAPI
/WebConsumer:
    get:
      description: Get a response from a web page
      responses:
        200:
          body:
            application/json:
    post:
      description: Get some result
      body:
          application/json:
            example: | 
              {
                 "valueToConvert" : 1,
                 "toUnit"    : "pounds",
                 "fromUnit"  : "newtons"
              }
      responses:
        200: 
          body: 
            application/json:
              example: |
                { 
                    "code" : 200
                    "message" : "This is correct"
                }
